### ISSUE TITLE
Error during build process

### ISSUE THREAD

**Issue by cogitas3d** [AOT-AG/DicomToMesh#2]
Hey there!

How are you? I hope very well.

I'm trying to compilet the source but I found som problems.

1) I clone the source.
2) I created a build directory
3) cmake . ..
4) The output of terminal (Linux Ubuntu 17.04):
`-- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is GNU 6.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/cogitas3d/Programs/DicomToMesh/build`

5) make

6) The output:
`Scanning dependencies of target dicom2meshlib
[ 16%] Building CXX object lib/CMakeFiles/dicom2meshlib.dir/src/vtkDicomRoutines.cpp.o
[ 33%] Building CXX object lib/CMakeFiles/dicom2meshlib.dir/src/vtkMeshRoutines.cpp.o
/home/cogitas3d/Programs/DicomToMesh/lib/src/vtkMeshRoutines.cpp: In member function ‘void VTKMeshRoutines::removeSmallObjects(vtkSmartPointer<vtkPolyData>, const double&)’:
/home/cogitas3d/Programs/DicomToMesh/lib/src/vtkMeshRoutines.cpp:127:24: error: invalid use of incomplete type ‘class vtkIdTypeArray’
         if( regionSizes->GetValue(regions) > maxSize )
                        ^~
In file included from /usr/include/vtk-6.3/vtkDataArray.h:38:0,
                 from /usr/include/vtk-6.3/vtkPoints.h:26,
                 from /usr/include/vtk-6.3/vtkPointSet.h:32,
                 from /usr/include/vtk-6.3/vtkPolyData.h:58,
                 from /usr/include/vtk-6.3/vtkPolyDataAlgorithm.h:33,
                 from /usr/include/vtk-6.3/vtkTransformPolyDataFilter.h:38,
                 from /home/cogitas3d/Programs/DicomToMesh/lib/src/vtkMeshRoutines.cpp:26:
/usr/include/vtk-6.3/vtkAbstractArray.h:51:7: note: forward declaration of ‘class vtkIdTypeArray’
 class vtkIdTypeArray;
       ^~~~~~~~~~~~~~
/home/cogitas3d/Programs/DicomToMesh/lib/src/vtkMeshRoutines.cpp:128:34: error: invalid use of incomplete type ‘class vtkIdTypeArray’
             maxSize = regionSizes->GetValue(regions);
                                  ^~
In file included from /usr/include/vtk-6.3/vtkDataArray.h:38:0,
                 from /usr/include/vtk-6.3/vtkPoints.h:26,
                 from /usr/include/vtk-6.3/vtkPointSet.h:32,
                 from /usr/include/vtk-6.3/vtkPolyData.h:58,
                 from /usr/include/vtk-6.3/vtkPolyDataAlgorithm.h:33,
                 from /usr/include/vtk-6.3/vtkTransformPolyDataFilter.h:38,
                 from /home/cogitas3d/Programs/DicomToMesh/lib/src/vtkMeshRoutines.cpp:26:
/usr/include/vtk-6.3/vtkAbstractArray.h:51:7: note: forward declaration of ‘class vtkIdTypeArray’
 class vtkIdTypeArray;
       ^~~~~~~~~~~~~~
/home/cogitas3d/Programs/DicomToMesh/lib/src/vtkMeshRoutines.cpp:134:24: error: invalid use of incomplete type ‘class vtkIdTypeArray’
         if( regionSizes->GetValue(regions) > maxSize * ratio )
                        ^~
In file included from /usr/include/vtk-6.3/vtkDataArray.h:38:0,
                 from /usr/include/vtk-6.3/vtkPoints.h:26,
                 from /usr/include/vtk-6.3/vtkPointSet.h:32,
                 from /usr/include/vtk-6.3/vtkPolyData.h:58,
                 from /usr/include/vtk-6.3/vtkPolyDataAlgorithm.h:33,
                 from /usr/include/vtk-6.3/vtkTransformPolyDataFilter.h:38,
                 from /home/cogitas3d/Programs/DicomToMesh/lib/src/vtkMeshRoutines.cpp:26:
/usr/include/vtk-6.3/vtkAbstractArray.h:51:7: note: forward declaration of ‘class vtkIdTypeArray’
 class vtkIdTypeArray;
       ^~~~~~~~~~~~~~
/home/cogitas3d/Programs/DicomToMesh/lib/src/vtkMeshRoutines.cpp: In static member function ‘static void VTKMeshRoutines::computeVertexNormalsTrivial(const vtkSmartPointer<vtkPolyData>&, std::vector<vtkVector3d>&)’:
/home/cogitas3d/Programs/DicomToMesh/lib/src/vtkMeshRoutines.cpp:199:31: error: invalid use of incomplete type ‘class vtkIdList’
         vtkIdType v0Idx = face->GetId(0);
                               ^~
In file included from /usr/include/vtk-6.3/vtkPointSet.h:30:0,
                 from /usr/include/vtk-6.3/vtkPolyData.h:58,
                 from /usr/include/vtk-6.3/vtkPolyDataAlgorithm.h:33,
                 from /usr/include/vtk-6.3/vtkTransformPolyDataFilter.h:38,
                 from /home/cogitas3d/Programs/DicomToMesh/lib/src/vtkMeshRoutines.cpp:26:
/usr/include/vtk-6.3/vtkDataSet.h:48:7: note: forward declaration of ‘class vtkIdList’
 class vtkIdList;
       ^~~~~~~~~
/home/cogitas3d/Programs/DicomToMesh/lib/src/vtkMeshRoutines.cpp:200:31: error: invalid use of incomplete type ‘class vtkIdList’
         vtkIdType v1Idx = face->GetId(1);
                               ^~
In file included from /usr/include/vtk-6.3/vtkPointSet.h:30:0,
                 from /usr/include/vtk-6.3/vtkPolyData.h:58,
                 from /usr/include/vtk-6.3/vtkPolyDataAlgorithm.h:33,
                 from /usr/include/vtk-6.3/vtkTransformPolyDataFilter.h:38,
                 from /home/cogitas3d/Programs/DicomToMesh/lib/src/vtkMeshRoutines.cpp:26:
/usr/include/vtk-6.3/vtkDataSet.h:48:7: note: forward declaration of ‘class vtkIdList’
 class vtkIdList;
       ^~~~~~~~~
/home/cogitas3d/Programs/DicomToMesh/lib/src/vtkMeshRoutines.cpp:201:31: error: invalid use of incomplete type ‘class vtkIdList’
         vtkIdType v2Idx = face->GetId(2);
                               ^~
In file included from /usr/include/vtk-6.3/vtkPointSet.h:30:0,
                 from /usr/include/vtk-6.3/vtkPolyData.h:58,
                 from /usr/include/vtk-6.3/vtkPolyDataAlgorithm.h:33,
                 from /usr/include/vtk-6.3/vtkTransformPolyDataFilter.h:38,
                 from /home/cogitas3d/Programs/DicomToMesh/lib/src/vtkMeshRoutines.cpp:26:
/usr/include/vtk-6.3/vtkDataSet.h:48:7: note: forward declaration of ‘class vtkIdList’
 class vtkIdList;
       ^~~~~~~~~
/home/cogitas3d/Programs/DicomToMesh/lib/src/vtkMeshRoutines.cpp: In member function ‘void VTKMeshRoutines::exportAsObjFile(const vtkSmartPointer<vtkPolyData>&, const string&)’:
/home/cogitas3d/Programs/DicomToMesh/lib/src/vtkMeshRoutines.cpp:270:31: error: invalid use of incomplete type ‘class vtkIdList’
         long long v0Idx = face->GetId(0); long long v1Idx = face->GetId(1); long long v2Idx = face->GetId(2);
                               ^~
In file included from /usr/include/vtk-6.3/vtkPointSet.h:30:0,
                 from /usr/include/vtk-6.3/vtkPolyData.h:58,
                 from /usr/include/vtk-6.3/vtkPolyDataAlgorithm.h:33,
                 from /usr/include/vtk-6.3/vtkTransformPolyDataFilter.h:38,
                 from /home/cogitas3d/Programs/DicomToMesh/lib/src/vtkMeshRoutines.cpp:26:
/usr/include/vtk-6.3/vtkDataSet.h:48:7: note: forward declaration of ‘class vtkIdList’
 class vtkIdList;
       ^~~~~~~~~
/home/cogitas3d/Programs/DicomToMesh/lib/src/vtkMeshRoutines.cpp:270:65: error: invalid use of incomplete type ‘class vtkIdList’
         long long v0Idx = face->GetId(0); long long v1Idx = face->GetId(1); long long v2Idx = face->GetId(2);
                                                                 ^~
In file included from /usr/include/vtk-6.3/vtkPointSet.h:30:0,
                 from /usr/include/vtk-6.3/vtkPolyData.h:58,
                 from /usr/include/vtk-6.3/vtkPolyDataAlgorithm.h:33,
                 from /usr/include/vtk-6.3/vtkTransformPolyDataFilter.h:38,
                 from /home/cogitas3d/Programs/DicomToMesh/lib/src/vtkMeshRoutines.cpp:26:
/usr/include/vtk-6.3/vtkDataSet.h:48:7: note: forward declaration of ‘class vtkIdList’
 class vtkIdList;
       ^~~~~~~~~
/home/cogitas3d/Programs/DicomToMesh/lib/src/vtkMeshRoutines.cpp:270:99: error: invalid use of incomplete type ‘class vtkIdList’
 long v0Idx = face->GetId(0); long long v1Idx = face->GetId(1); long long v2Idx = face->GetId(2);
                                                                                      ^~
In file included from /usr/include/vtk-6.3/vtkPointSet.h:30:0,
                 from /usr/include/vtk-6.3/vtkPolyData.h:58,
                 from /usr/include/vtk-6.3/vtkPolyDataAlgorithm.h:33,
                 from /usr/include/vtk-6.3/vtkTransformPolyDataFilter.h:38,
                 from /home/cogitas3d/Programs/DicomToMesh/lib/src/vtkMeshRoutines.cpp:26:
/usr/include/vtk-6.3/vtkDataSet.h:48:7: note: forward declaration of ‘class vtkIdList’
 class vtkIdList;
       ^~~~~~~~~
In file included from /home/cogitas3d/Programs/DicomToMesh/lib/inc/vtkMeshRoutines.h:27:0,
                 from /home/cogitas3d/Programs/DicomToMesh/lib/src/vtkMeshRoutines.cpp:41:
/usr/include/vtk-6.3/vtkSmartPointer.h: In instantiation of ‘static vtkSmartPointer<T> vtkSmartPointer<T>::New() [with T = vtkIdList]’:
/home/cogitas3d/Programs/DicomToMesh/lib/src/vtkMeshRoutines.cpp:197:71:   required from here
/usr/include/vtk-6.3/vtkSmartPointer.h:117:37: error: incomplete type ‘vtkIdList’ used in nested name specifier
     return vtkSmartPointer<T>(T::New(), NoReference());
                               ~~~~~~^~
/usr/include/vtk-6.3/vtkSmartPointer.h: In instantiation of ‘vtkSmartPointer<T>::operator T*() const [with T = vtkIdList]’:
/home/cogitas3d/Programs/DicomToMesh/lib/src/vtkMeshRoutines.cpp:198:35:   required from here
/usr/include/vtk-6.3/vtkSmartPointer.h:79:12: error: invalid static_cast from type ‘vtkObjectBase* const’ to type ‘vtkIdList*’
     return static_cast<T*>(this->Object);
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/vtk-6.3/vtkSmartPointer.h: In instantiation of ‘T* vtkSmartPointer<T>::operator->() const [with T = vtkIdList]’:
/home/cogitas3d/Programs/DicomToMesh/lib/src/vtkMeshRoutines.cpp:199:31:   required from here
/usr/include/vtk-6.3/vtkSmartPointer.h:94:12: error: invalid static_cast from type ‘vtkObjectBase* const’ to type ‘vtkIdList*’
     return static_cast<T*>(this->Object);
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
lib/CMakeFiles/dicom2meshlib.dir/build.make:86: recipe for target 'lib/CMakeFiles/dicom2meshlib.dir/src/vtkMeshRoutines.cpp.o' failed
make[2]: *** [lib/CMakeFiles/dicom2meshlib.dir/src/vtkMeshRoutines.cpp.o] Error 1
CMakeFiles/Makefile2:122: recipe for target 'lib/CMakeFiles/dicom2meshlib.dir/all' failed
make[1]: *** [lib/CMakeFiles/dicom2meshlib.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
`

I'm trying to import DICOM directly in Blender 3D, this project could help us do it.

Thank you for the attention!

**Comment by eidelen** [comment]
Hi,
I added the two missing includes to vtkMeshRoutines.cpp. Can you git pull and try again?
Actually, you use quite an old version of vtk.  I am working with 7.1.1 and 8.0.1
As you might have seen, I just added build instructions for Linux to the readme file. Instead of using just cmake, I'm using the command ccmake (two c)... like that you can change and check cmake project settings.

**Comment by cogitas3d** [comment]
Wow! It works perfectly, thank you!
